apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"run":"my-nginx"},"name":"my-nginx","namespace":"default"},"spec":{"ports":[{"port":80,"protocol":"TCP"}],"selector":{"run":"my-nginx"}}}
  creationTimestamp: "2019-05-12T16:22:19Z"
  labels:
    run: my-nginx
  name: my-nginx
  namespace: default
  resourceVersion: "853739"
  selfLink: /api/v1/namespaces/default/services/my-nginx
  uid: 1d115c8c-74d2-11e9-98e2-427dc4577549
spec:
  clusterIP: 10.245.104.7
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 31836
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    run: my-nginx
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: 159.203.159.52
